### ISSUE TITLE
The auction duration is hardcoded?

### ISSUE THREAD

**Issue by iemejia** [iemejia/beam#14]
We have to investigate if the auction duration is hardcoded or why the time is always like this:
```
  017-02-03T13:53:30.064Z Generating 10000 events in batch mode
  2017-02-03T13:53:30.070Z Expected auction duration is 16667 ms
```

**Comment by echauchot** [comment]
in query 9 we put bids into custom windows that are merged in the end. But we don't know with only a bids collection that the related auction is over or not, so we put bids in a window that ends at expected auction duration (statistical max auction duration computed out of generator configuration) to give time to the bid to be merged.
