### ISSUE TITLE
QueryTest is broken

### ISSUE THREAD

**Issue by iemejia** [iemejia/beam#15]

**Comment by echauchot** [comment]
linked to #22

**Comment by echauchot** [comment]
temporary fix: each Generator thread (BoundedEventSource) generates a part of events dataset.  For default 100 threads and test dataset of size 100, each thread generates only one event of timestamp baseTime + 0 sec. So every event has the timestamp=baseTime contrary to expected dataset (generator with a single java thread without using BoundedEventSource) that have a timestamp=baseTime + n. Need a fix the timeStamp generaion in BoundedEventSource

**Comment by echauchot** [comment]
Closed because the last related issue #22
