### ISSUE TITLE
Improve some queries implementation

### ISSUE THREAD

**Issue by echauchot** [iemejia/beam#18]
See TODO in query 10 and query 11 and query5

**Comment by iemejia** [comment]
This refers to improvements on queries, or weird things, e.g. extra lifting or groupby key

**Comment by echauchot** [comment]
Correct

**Comment by echauchot** [comment]
Query 10: the keying with null key + strange groupByKey is there to allow 1 output file per window.

**Comment by echauchot** [comment]
split this ticket for each query: 
see #30
see #31
see #32
