### ISSUE TITLE
find an equivalent of dataflow checkWatermarks method used in NexmarkRunner.monitor()

### ISSUE THREAD

**Issue by echauchot** [iemejia/beam#19]

**Comment by iemejia** [comment]
@echauchot This is for which query concretely or which part ?

**Comment by echauchot** [comment]
it was used in dataflow monitor in NexmarkRunner, updating title

**Comment by echauchot** [comment]
previous version of `monitor()` was dataflow oriented and used that `checkWatermarks()` method that is not available on other runners. Now that `monitor()` is compatible with all the runners, we removed this method. We need to test in dataflow if the generic `monitor()` behaves normally and if not, override `monitor()` in `NexMarkGoogleRunner`

**Comment by echauchot** [comment]
removed dataflow specific methods from NexmarkRunner
