### ISSUE TITLE
Add a query that uses the state and timer APIs

### ISSUE THREAD

**Issue by echauchot** [iemejia/beam#29]

**Comment by echauchot** [comment]
Support of timer API is partial among runners:
- direct: supported
- flink: supported
- dataflow: supported
- spark: not supported
- apex: not supported

**Comment by echauchot** [comment]
use case: abuse detection, if a user does 10 auctions log it. uses state to have exact batching. uses timer to detect the end of the window.

**Comment by iemejia** [comment]
This is marked invalid because it is not needed because #7 covers the case.
