### ISSUE TITLE
all queries: flink never stops in streaming mode, timeout/waitUntilFinish not supported

### ISSUE THREAD

**Issue by echauchot** [iemejia/beam#49]
https://issues.apache.org/jira/browse/BEAM-593
Need standardization among runners on pipeline termination:
https://lists.apache.org/thread.html/86831496a08fe148e3b982cdb904f828f262c0b571543a9fed7b915d@%3Cdev.beam.apache.org%3E

**Comment by iemejia** [comment]
Fixed in upstream, if watermark is infinite it ends and we can recover the metrics.
