### ISSUE TITLE
Query3 should be migrated to use the new State api

### ISSUE THREAD

**Issue by iemejia** [iemejia/beam#7]
To be discussed in each specific case.

**Comment by echauchot** [comment]
Query 3

**Comment by echauchot** [comment]
Support of state API is partial among runners:
- direct: supported
- flink: supported
- dataflow: supported
- spark: not supported
- apex: not supported

**Comment by echauchot** [comment]
- Migration to state api: done
- Need to improve test because it passed with state desactivated

**Comment by echauchot** [comment]
Applicative join on CoGBKResult. Content of a given window
 | with State | without State 
 --------------------------------- | ------------- | ------------------ 
 no person event received |  output if person event already received before | no output 
 no auction event received | output if auction event already received before | no output 

**"before"** means in a previous window. But state is scoped by the current window beging processed so it make no difference to use state or not. That is why tests results don't change if we enable state or not? Ask Mark and maybe Kenn

**Comment by echauchot** [comment]
state is indeed useless for this query so remove it. Besides, the generator dataset does not seem to need it (auctions and persons seem to all be in the same window) because unit test passes without state enabled.

**Comment by echauchot** [comment]
Well, actually, the original query in the PR was implemented using fixed windowing of 10 seconds but IMHO it might make more sense to use sliding windows to provide updates of "who as been selling in the US for the last hour". But either ways, state will not go through windows for now, so I will implement it with a global window. As there are already others queries (query7, query8, query10) to illustrate fixed windowing, it is OK to illustrate only state (+ timers) in query3.

**Comment by echauchot** [comment]
https://issues.apache.org/jira/browse/BEAM-1261
